# Generated by Django 5.1.6 on 2025-02-28 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('credenciales', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(max_length=10)),
                ('peso', models.FloatField()),
                ('categoria', models.CharField(max_length=50)),
                ('experiencia', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simetria', models.FloatField()),
                ('definicion', models.FloatField()),
                ('comentarios', models.TextField()),
                ('juez', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participantes.juez')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participantes.participante')),
            ],
        ),
    ]
